services:
  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}
      - CONFIG_SERVER_PASSWORD=${CONFIG_SERVER_PASSWORD:-configpassword}
    networks:
      - yobel-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "--user", "configuser:${CONFIG_SERVER_PASSWORD:-configpassword}", "http://localhost:8888/actuator/health" ]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 60s

  service-discovery:
    build:
      context: ./service-discovery
      dockerfile: Dockerfile
    container_name: service-discovery
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}
      - CONFIG_SERVER_PASSWORD=${CONFIG_SERVER_PASSWORD:-configpassword}
      - SPRING_CONFIG_IMPORT=optional:configserver:http://configuser:${CONFIG_SERVER_PASSWORD:-configpassword}@config-server:8888
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - yobel-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  yobel-network:
    driver: bridge
